project:
  type: website

website:
  title: "<b>OTexts</b>: Online, open-access textbooks"
  site-url: "https://OTexts.com"
  favicon: img/favicon.ico
  open-graph: true
  search: false
  google-analytics: "G-JKBLG3XQGY"
  navbar:
    background: "#536878"
    logo: img/OTexts.png
  page-footer:
    left: "&copy; OTexts, Melbourne, Australia. 2008-[]{#current-year}"
    background: "#536878"
    right: Made with [Quarto](https://quarto.org)

date-format: "D MMMM YYYY"

format:
  html:
    theme: tango
    css: styles.css
    toc: true
    mainfont: "Fira Sans"
    grid:
      margin-width: 0px
    include-in-header:
      file: header.html
    include-after-body:
      - text: |
          <script>
            document.getElementById('current-year').textContent = new Date().getFullYear();
          </script>
